name: debug
on:
  workflow_call: {}
jobs:
  job:
    name: debug (${{ github.event_name }})
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: setupNode
        uses: actions/setup-node@v3.6.0
        with:
          node-version: current
      - name: prepare
        id: prepare
        shell: bash
        run: |
          printf 'homeFolder=%s\n' "$(realpath ~)" >> $GITHUB_OUTPUT
          printf 'cwdFolder=%s\n' "$(realpath .)" >> $GITHUB_OUTPUT
          printf 'cwdParentFolder=%s\n' "$(realpath ..)" >> $GITHUB_OUTPUT
          printf 'workspaceFolder=%s\n' "$(realpath "$GITHUB_WORKSPACE")" >> $GITHUB_OUTPUT
          printf 'tempFolder=%s\n' "$(realpath "$RUNNER_TEMP")" >> $GITHUB_OUTPUT
      - name: checkout
        uses: actions/checkout@v3.5.2
      - name: installNodePackages
        id: installNodePackages
        uses: jaid/action-npm-install@main
      - name: installPackages
        uses: awalsh128/cache-apt-pkgs-action@v1.3.0
        with:
          packages: jq
      - name: users
        shell: bash
        run: |
          set -o xtrace
          cat /etc/passwd
      - name: groups
        shell: bash
        run: |
          set -o xtrace
          cat /etc/group
      - name: whoami
        shell: bash
        run: |
          set -o xtrace
          whoami
      - name: myGroups
        shell: bash
        run: |
          set -o xtrace
          groups
      - name: dumpContext (strategy)
        shell: bash
        env:
          object: ${{ toJson(strategy) }}
        run: |
          set -o xtrace
          jq --indent 2 --color-output . <<< "$object"
      - name: dumpContext (matrix)
        shell: bash
        env:
          object: ${{ toJson(env) }}
        run: |
          set -o xtrace
          jq --indent 2 --color-output . <<< "$object"
      - name: dumpContext (vars)
        shell: bash
        env:
          object: ${{ toJson(vars) }}
        run: |
          set -o xtrace
          jq --indent 2 --color-output . <<< "$object"
      - name: dumpContext (github)
        shell: bash
        env:
          object: ${{ toJson(github) }}
        run: |
          set -o xtrace
          jq --indent 2 --color-output . <<< "$object"
      - name: dumpContext (job)
        shell: bash
        env:
          object: ${{ toJson(job) }}
        run: |
          set -o xtrace
          jq --indent 2 --color-output . <<< "$object"
      - name: dumpContext (steps)
        shell: bash
        env:
          object: ${{ toJson(steps) }}
        run: |
          set -o xtrace
          jq --indent 2 --color-output . <<< "$object"
      - name: dumpContext (runner)
        shell: bash
        env:
          object: ${{ toJson(runner) }}
        run: |
          set -o xtrace
          jq --indent 2 --color-output . <<< "$object"
      - id: actionsGithubContext
        name: '@actions/github context'
        run: node --import tsx .github/workflows/debug-overlay/actionsGithubContext.ts
      - name: env
        shell: bash
        run: |
          styleBlue=$(TERM=xterm-256color tput setaf 6)
          styleOrange=$(TERM=xterm-256color tput setaf 172)
          styleReset=$(TERM=xterm-256color tput sgr0)
          keys=($(printenv | cut -d'=' -f1))
          sortedKeys=($(printf '%s\n' "${keys[@]}" | tr ' ' '\n' | sort -df))
          for key in "${sortedKeys[@]}"; do
            declare value=$(printenv "$key")
            printf "$styleOrange%s$styleReset: $styleBlue%s$styleReset\n" "$key" "$value"
          done
      - name: osRelease
        shell: bash
        env:
          TERM: xterm-256color
        run: |
          styleBlue=$(tput setaf 6)
          styleOrange=$(tput setaf 172)
          styleReset=$(tput sgr0)
          osRelease=$(cat /etc/os-release)
          keys=($(printf %s "$osRelease" | cut --fields 1 --delimiter = | sort))
          for key in "${keys[@]}"; do
            # declare version=$(dpkg --status "$key" | grep --extended-regexp "^Version:" | cut --fields 2- --delimiter ' ')
            declare value=$(printf %s "$osRelease" | grep --extended-regexp "^$key=" | cut --fields 2- --delimiter =)
            if [[ ${value:0:1} == '"' ]]; then
              value=${value:1:-1}
            fi
            printf "$styleOrange%s$styleReset: $styleBlue%s$styleReset\n" "$key" "$value"
          done
      - name: ubuntuPackages
        shell: bash
        env:
          TERM: xterm-256color
        run: |
          styleBlue=$(tput setaf 6)
          styleOrange=$(tput setaf 172)
          styleReset=$(tput sgr0)
          keys=($(dpkg --get-selections | grep --invert-match deinstall | cut --fields 1))
          for key in "${keys[@]}"; do
            declare version=$(dpkg --status "$key" | grep --extended-regexp "^Version:" | cut --fields 2- --delimiter ' ')
            printf "$styleOrange%s$styleReset: $styleBlue%s$styleReset\n" "$key" "$version"
          done
      - name: pythonPackages
        shell: bash
        env:
          TERM: xterm-256color
        run: |
          styleBlue=$(tput setaf 6)
          styleOrange=$(tput setaf 172)
          styleReset=$(tput sgr0)
          while read -r line; do
            package=$(printf %s "$line" | cut --delimiter ' ' --fields 1)
            version=$(printf %s "$line" | cut --delimiter ' ' --fields 2-)
            printf "$styleOrange%s$styleReset: $styleBlue%s$styleReset\n" "$package" "$version"
          done < <(pip list | sed '1,2d')
      - name: nodePackages
        shell: bash
        env:
          TERM: xterm-256color
        run: |
          styleBlue=$(tput setaf 6)
          styleOrange=$(tput setaf 172)
          styleReset=$(tput sgr0)
          while read -r line; do
          package=$(printf %s "$line" | cut --delimiter ' ' --fields 1)
          version=$(printf %s "$line" | cut --delimiter ' ' --fields 2-)
              printf "$styleOrange%s$styleReset: $styleBlue%s$styleReset\n" "$package" "$version"
          done < <(npm list --depth 0 --global --json | jq --raw-output '.dependencies | to_entries[] | "\(.key) \(.value.version)"')
      - name: commands
        shell: bash
        env:
          TERM: xterm-256color
        run: |
          styleBlue=$(tput setaf 6)
          styleOrange=$(tput setaf 172)
          styleReset=$(tput sgr0)
          IFS=: read -ra paths <<< "$PATH"
          declare -a foundCommands
          for folder in "${paths[@]}"; do
            if [[ -d $folder ]]; then
              files=()
              while read -r -d $'\0' file; do
                files+=("$file")
              done < <(find "$folder" -maxdepth 1 -type f -executable -printf '%P\0')
              sortedFiles=($(printf '%s\n' "${files[@]}" | sort -d))
              if [[ ${#files[@]} -ge 1 ]]; then
                printf "$styleOrange%s$styleReset (%s)\n" "$folder" "${#files[@]}"
                for file in "${sortedFiles[@]}"; do
                  if [[ ! " ${foundCommands[*]} " =~ " ${file} " ]]; then
                    printf "$styleBlue%s$styleReset\n" "$file"
                    foundCommands+=("$file")
                  fi
                done
              fi
            fi
          done
      - id: lsHome
        if: ${{ steps.prepare.outcome == 'success' && steps.prepare.outputs.homeFolder != '' }}
        name: ðŸ“‚ ${{ steps.prepare.outputs.homeFolder }} (home)
        shell: bash
        env:
          TERM: xterm-256color
          target: ${{ steps.prepare.outputs.homeFolder }}
        working-directory: ${{ steps.prepare.outputs.homeFolder }}
        run: |
          set -o xtrace
          du --apparent-size --summarize --bytes "$target"
          ls -l --almost-all --color=always --si --literal --group-directories-first
      - id: lsCwd
        if: ${{ steps.prepare.outcome == 'success' && steps.prepare.outputs.cwdFolder != '' }}
        name: ðŸ“‚ ${{ steps.prepare.outputs.cwdFolder }} (cwd)
        shell: bash
        env:
          TERM: xterm-256color
          target: ${{ steps.prepare.outputs.cwdFolder }}
        working-directory: ${{ steps.prepare.outputs.cwdFolder }}
        run: |
          set -o xtrace
          du --apparent-size --summarize --bytes "$target"
          ls -l --almost-all --color=always --si --literal --group-directories-first
      - id: lsCwdParent
        if: ${{ steps.prepare.outcome == 'success' && steps.prepare.outputs.cwdParentFolder != '' }}
        name: ðŸ“‚ ${{ steps.prepare.outputs.cwdParentFolder }} (cwdParent)
        shell: bash
        env:
          TERM: xterm-256color
          target: ${{ steps.prepare.outputs.cwdParentFolder }}
        working-directory: ${{ steps.prepare.outputs.cwdParentFolder }}
        run: |
          set -o xtrace
          du --apparent-size --summarize --bytes "$target"
          ls -l --almost-all --color=always --si --literal --group-directories-first
      - id: lsWorkspace
        if: ${{ steps.prepare.outcome == 'success' && steps.prepare.outputs.workspaceFolder != '' }}
        name: ðŸ“‚ ${{ steps.prepare.outputs.workspaceFolder }} (workspace)
        shell: bash
        env:
          TERM: xterm-256color
          target: ${{ steps.prepare.outputs.workspaceFolder }}
        working-directory: ${{ steps.prepare.outputs.workspaceFolder }}
        run: |
          set -o xtrace
          du --apparent-size --summarize --bytes "$target"
          ls -l --almost-all --color=always --si --literal --group-directories-first
      - id: lsTemp
        if: ${{ steps.prepare.outcome == 'success' && steps.prepare.outputs.tempFolder != '' }}
        name: ðŸ“‚ ${{ steps.prepare.outputs.tempFolder }} (temp)
        shell: bash
        env:
          TERM: xterm-256color
          target: ${{ steps.prepare.outputs.tempFolder }}
        working-directory: ${{ steps.prepare.outputs.tempFolder }}
        run: |
          set -o xtrace
          du --apparent-size --summarize --bytes "$target"
          ls -l --almost-all --color=always --si --literal --group-directories-first